### ISSUE TITLE
Is an install Info missing?

### ISSUE THREAD

**Issue by strangerattractor** [keijiro/KinoFeedback2#1]
Hey Keijiro, 

might there be some key-info missing for installation or use of this package? Just installed this to my project, and adding the script to the camera doesn't do anything, also if I tweak it. Just added it to your Dxrtest scenes as well, and it doesn't feedback there either. Sorry if I'm missing something totally obvious here!

Also: Thank you so much! have been looking for an elegant solution to this!!! Was fiddeling with secondery cameras and additional back-screen before... so this should be perfect.

**Comment by keijiro** [comment]
This effect is implemented as a custom pass, not a camera effect. See the manual (below) and how I set it up in the example project.

https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@8.2/manual/Custom-Pass.html

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
